name: 'CI: pyMalleableProfileParser'

on:
  # manual trigger
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'mpp/**'
      - 'setup.py'

jobs:
  python-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        fail-fast: false
        os: [ ubuntu-latest ]
        python: [3.7, 3.8, 3.9, 3.10]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install pyMalleableProfileParser
        run: pip3 setup .

      - name: Run Tests
        run: python3 -m unittest tests/test.py
