name: 'CI: pyMalleableProfileParser'

on:
  # manual trigger
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mpp/**'
      - 'tests/**'
      - 'poetry.lock'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
      - 'mpp/**'
      - 'tests/**'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  # Build
  python-test:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
          cache: poetry

      - name: Install pyMalleableProfileParser
        run: poetry install --no-interaction --no-ansi

      - name: Run Tests
        run: poetry run pytest --cov mpp

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == 3.9 }}
